name: Deploy EZ Saga Admin to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: apps/frontend/node_modules
          key: ${{ runner.os }}-ezsaga-frontend-${{ hashFiles('apps/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-ezsaga-frontend-
      
      - name: Clean previous export
        run: rm -rf out        

      - name: Install dependencies
        run: npm install

      - name: Build and export static site
        run: |
          NODE_ENV=production npm run build
          echo '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url=/ez-saga/"></head><body></body></html>' > out/index.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: apps/frontend/out