name: CICD For EZ Saga Admin Website - Memo.bond

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  deploy:
    # Add a dependency to the build job
    runs-on: ubuntu-latest
    environment:
      name: Vercel Credentials
    defaults:
      run:
        working-directory: apps/frontend
    
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-

      # Install dependencies
      - name: Install dependencies
        run: npm install              

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Build and deploy to Vercel
        run: |
          export VERCEL_ORG_ID=team_yYZLMzdCB34ZGt0X8OJOR6Ry
          export VERCEL_PROJECT_ID=prj_d302gwf5NEVV8t5TayQilFL7hAvW
          export VERCEL_TOKEN=EmSaY2n3oKuRJdJR7iAoM9ju
          vercel pull --yes
          vercel build --prod
          vercel deploy --prod --prebuilt --yes --token=$VERCEL_TOKEN